In [1]:
import pandas as pd

In [2]:
macros = pd.read_csv('/Users/jon/Desktop/Ironhack/Unit 7 - Final Project/Final-Project-Ironhack/Type of analysis/Time series analysis/macro/csv/macro_2009_2025.csv')
fundamentals = pd.read_csv('/Users/jon/Desktop/Ironhack/Unit 7 - Final Project/Final-Project-Ironhack/Type of analysis/Time series analysis/fundamentals/csv/servicenow/servicenow_quarterly_all_metrics.csv')
prices = pd.read_csv('/Users/jon/Desktop/Ironhack/Unit 7 - Final Project/Final-Project-Ironhack/Type of analysis/Time series analysis/prices/csv/now_price.csv')

In [3]:
fundamentals

,date,revenue_musd,net_income_musd,total_assets_musd,total_liabilities_musd,share_holder_equity_musd
0,2011-03-31,85.0,7.0,0.0,NaN,NaN
1,2011-06-30,29.0,0.0,0.0,0.0,0.0
2,2011-09-30,34.0,0.0,0.0,0.0,0.0
3,2011-12-31,39.0,-7.0,156.0,146.0,11.0
4,2012-03-31,47.0,-6.0,0.0,0.0,0.0
5,2012-06-30,57.0,-9.0,200.0,175.0,25.0
6,2012-09-30,64.0,-13.0,382.0,191.0,191.0
7,2012-12-31,75.0,-10.0,478.0,235.0,243.0
8,2013-03-31,86.0,-13.0,516.0,252.0,264.0
9,2013-06-30,102.0,-21.0,542.0,274.0,268.0
10,2013-09-30,111.0,-15.0,579.0,291.0,288.0
11,2013-12-31,125.0,-24.0,1168.0,774.0,394.0
12,2014-03-31,139.0,-43.0,1224.0,821.0,404.0
13,2014-06-30,167.0,-50.0,1262.0,864.0,398.0
14,2014-09-30,179.0,-41.0,1305.0,887.0,417.0
15,2014-12-31,198.0,-45.0,1425.0,996.0,429.0
16,2015-03-31,212.0,-58.0,1494.0,1039.0,455.0
17,2015-06-30,247.0,-62.0,1563.0,1100.0,463.0
18,2015-09-30,261.0,-41.0,1663.0,1146.0,517.0
19,2015-12-31,286.0,-37.0,1807.0,1240.0,567.0
20,2016-03-31,306.0,-333.0,1874.0,1572.0,302.0
21,2016-06-30,341.0,-50.0,1714.0,1390.0,324.0
22,2016-09-30,358.0,-36.0,1813.0,1451.0,363.0
23,2016-12-31,386.0,5.0,2034.0,1647.0,387.0
24,2017-03-31,429.0,-22.0,2170.0,1743.0,427.0
25,2017-06-30,448.0,-56.0,2924.0,2442.0,482.0
26,2017-09-30,492.0,-22.0,3070.0,2518.0,551.0
27,2017-12-31,549.0,-17.0,3550.0,2772.0,779.0
28,2018-03-31,589.0,11.0,3704.0,2839.0,865.0
29,2018-06-30,631.0,-53.0,3473.0,2581.0,892.0
30,2018-09-30,673.0,8.0,3581.0,2561.0,1020.0
31,2018-12-31,715.0,7.0,3879.0,2768.0,1111.0
32,2019-03-31,789.0,-2.0,4399.0,3204.0,1195.0
33,2019-06-30,834.0,-11.0,4603.0,3342.0,1261.0
34,2019-09-30,886.0,41.0,4757.0,3327.0,1429.0
35,2019-12-31,951.0,599.0,6022.0,3894.0,2128.0
36,2020-03-31,1046.0,48.0,6197.0,3931.0,2266.0
37,2020-06-30,1071.0,41.0,6521.0,4043.0,2479.0
38,2020-09-30,1152.0,13.0,7705.0,5032.0,2674.0
39,2020-12-31,1250.0,17.0,8715.0,5881.0,2834.0
40,2021-03-31,1360.0,82.0,8822.0,5785.0,3037.0
41,2021-06-30,1409.0,59.0,9187.0,5912.0,3275.0
42,2021-09-30,1512.0,63.0,9478.0,5944.0,3534.0
43,2021-12-31,1615.0,26.0,10798.0,7103.0,3695.0
44,2022-03-31,1722.0,75.0,10993.0,6996.0,3997.0
45,2022-06-30,1752.0,20.0,11102.0,6908.0,4194.0
46,2022-09-30,1831.0,80.0,11106.0,6583.0,4523.0
47,2022-12-31,1940.0,150.0,13299.0,8267.0,5032.0
48,2023-03-31,2096.0,150.0,13614.0,8014.0,5600.0
49,2023-06-30,2150.0,1044.0,14923.0,7997.0,6926.0
50,2023-09-30,2288.0,242.0,15091.0,7909.0,7182.0
51,2023-12-31,2437.0,295.0,17387.0,9759.0,7628.0
52,2024-03-31,2603.0,347.0,17544.0,9437.0,8107.0
53,2024-06-30,2627.0,262.0,18207.0,9541.0,8666.0
54,2024-09-30,2797.0,432.0,18434.0,9144.0,9290.0
55,2024-12-31,2957.0,384.0,20383.0,10774.0,9609.0
56,2025-03-31,3088.0,460.0,20972.0,10833.0,10139.0
57,2025-06-30,3215.0,385.0,22051.0,11119.0,10932.0
58,2025-09-30,3407.0,502.0,21789.0,10488.0,11301.0
59,2025-12-31,3568.0,401.0,NaN,NaN,NaN

In [4]:
macros = macros.sort_values(by='date', ascending=True)
macros = macros.reset_index(drop=True)
macros

          date  gdp_growth  interest_rate
0   2009-03-31       -3.23           0.15
1   2009-06-30       -3.98           0.16
2   2009-09-30       -3.13           0.12
3   2009-12-31        0.11           0.11
4   2010-03-31        1.75           0.20
..         ...         ...            ...
61  2024-06-30        3.04           5.33
62  2024-09-30        2.72           4.83
63  2024-12-31        2.53           4.33
64  2025-03-31        1.99           4.33
65  2025-06-30        1.99           4.33

[66 rows x 3 columns]

In [5]:
prices

     Unnamed: 0        Date       Price calendar_quarter
0             0  2012-06-30    4.920000          Q2 2012
1             1  2012-07-31    5.400000          Q3 2012
2             2  2012-08-31    6.220000          Q3 2012
3             3  2012-09-30    7.736000          Q3 2012
4             4  2012-10-31    6.130000          Q4 2012
..          ...         ...         ...              ...
159         159  2025-09-30  184.056000          Q3 2025
160         160  2025-10-31  183.856003          Q4 2025
161         161  2025-11-30  162.481995          Q4 2025
162         162  2025-12-31  153.190002          Q4 2025
163         163  2026-01-31  117.010002          Q1 2026

[164 rows x 4 columns]

BEFORE MERGING MAKE SURE DATE COLUMN BETWEEN MACRO AND FUNDAMENTAL DATA CORRESPOND IF NOT THE DF WILL COME OUT EMPTY

In [6]:
#If dates on fundamentals coincide with macros, uncomment line 3, otherwise, use line 4 and 5. May have to adjust depending on the dataset.

#stock = pd.merge(funadamentals, macros, on='date', how='inner')
stock = pd.merge(fundamentals, macros, left_index=True, right_index=True, how="inner")
stock = stock.rename(columns={'date_x': 'date'})


stock

,date,revenue_musd,net_income_musd,total_assets_musd,total_liabilities_musd,share_holder_equity_musd,date_y,gdp_growth,interest_rate
0,2011-03-31,85.0,7.0,0.0,NaN,NaN,2009-03-31,-3.23,0.15
1,2011-06-30,29.0,0.0,0.0,0.0,0.0,2009-06-30,-3.98,0.16
2,2011-09-30,34.0,0.0,0.0,0.0,0.0,2009-09-30,-3.13,0.12
3,2011-12-31,39.0,-7.0,156.0,146.0,11.0,2009-12-31,0.11,0.11
4,2012-03-31,47.0,-6.0,0.0,0.0,0.0,2010-03-31,1.75,0.20
5,2012-06-30,57.0,-9.0,200.0,175.0,25.0,2010-06-30,2.91,0.18
6,2012-09-30,64.0,-13.0,382.0,191.0,191.0,2010-09-30,3.34,0.19
7,2012-12-31,75.0,-10.0,478.0,235.0,243.0,2010-12-31,2.78,0.17
8,2013-03-31,86.0,-13.0,516.0,252.0,264.0,2011-03-31,2.04,0.10
9,2013-06-30,102.0,-21.0,542.0,274.0,268.0,2011-06-30,1.74,0.07
10,2013-09-30,111.0,-15.0,579.0,291.0,288.0,2011-09-30,0.94,0.07
11,2013-12-31,125.0,-24.0,1168.0,774.0,394.0,2011-12-31,1.54,0.08
12,2014-03-31,139.0,-43.0,1224.0,821.0,404.0,2012-03-31,2.64,0.14
13,2014-06-30,167.0,-50.0,1262.0,864.0,398.0,2012-06-30,2.40,0.16
14,2014-09-30,179.0,-41.0,1305.0,887.0,417.0,2012-09-30,2.57,0.16
15,2014-12-31,198.0,-45.0,1425.0,996.0,429.0,2012-12-31,1.55,0.14
16,2015-03-31,212.0,-58.0,1494.0,1039.0,455.0,2013-03-31,1.70,0.15
17,2015-06-30,247.0,-62.0,1563.0,1100.0,463.0,2013-06-30,1.52,0.09
18,2015-09-30,261.0,-41.0,1663.0,1146.0,517.0,2013-09-30,2.24,0.09
19,2015-12-31,286.0,-37.0,1807.0,1240.0,567.0,2013-12-31,3.01,0.07
20,2016-03-31,306.0,-333.0,1874.0,1572.0,302.0,2014-03-31,1.65,0.09
21,2016-06-30,341.0,-50.0,1714.0,1390.0,324.0,2014-06-30,2.69,0.09
22,2016-09-30,358.0,-36.0,1813.0,1451.0,363.0,2014-09-30,3.06,0.09
23,2016-12-31,386.0,5.0,2034.0,1647.0,387.0,2014-12-31,2.69,0.11
24,2017-03-31,429.0,-22.0,2170.0,1743.0,427.0,2015-03-31,3.97,0.12
25,2017-06-30,448.0,-56.0,2924.0,2442.0,482.0,2015-06-30,3.28,0.13
26,2017-09-30,492.0,-22.0,3070.0,2518.0,551.0,2015-09-30,2.45,0.12
27,2017-12-31,549.0,-17.0,3550.0,2772.0,779.0,2015-12-31,2.12,0.34
28,2018-03-31,589.0,11.0,3704.0,2839.0,865.0,2016-03-31,1.80,0.37
29,2018-06-30,631.0,-53.0,3473.0,2581.0,892.0,2016-06-30,1.49,0.39
30,2018-09-30,673.0,8.0,3581.0,2561.0,1020.0,2016-09-30,1.81,0.40
31,2018-12-31,715.0,7.0,3879.0,2768.0,1111.0,2016-12-31,2.18,0.65
32,2019-03-31,789.0,-2.0,4399.0,3204.0,1195.0,2017-03-31,2.09,0.90
33,2019-06-30,834.0,-11.0,4603.0,3342.0,1261.0,2017-06-30,2.33,1.15
34,2019-09-30,886.0,41.0,4757.0,3327.0,1429.0,2017-09-30,2.41,1.15
35,2019-12-31,951.0,599.0,6022.0,3894.0,2128.0,2017-12-31,2.99,1.41
36,2020-03-31,1046.0,48.0,6197.0,3931.0,2266.0,2018-03-31,3.33,1.69
37,2020-06-30,1071.0,41.0,6521.0,4043.0,2479.0,2018-06-30,3.30,1.91
38,2020-09-30,1152.0,13.0,7705.0,5032.0,2674.0,2018-09-30,3.13,2.19
39,2020-12-31,1250.0,17.0,8715.0,5881.0,2834.0,2018-12-31,2.13,2.40
40,2021-03-31,1360.0,82.0,8822.0,5785.0,3037.0,2019-03-31,1.93,2.42
41,2021-06-30,1409.0,59.0,9187.0,5912.0,3275.0,2019-06-30,2.24,2.40
42,2021-09-30,1512.0,63.0,9478.0,5944.0,3534.0,2019-09-30,2.80,1.83
43,2021-12-31,1615.0,26.0,10798.0,7103.0,3695.0,2019-12-31,3.35,1.55
44,2022-03-31,1722.0,75.0,10993.0,6996.0,3997.0,2020-03-31,1.28,0.05
45,2022-06-30,1752.0,20.0,11102.0,6908.0,4194.0,2020-06-30,-7.50,0.09
46,2022-09-30,1831.0,80.0,11106.0,6583.0,4523.0,2020-09-30,-1.41,0.09
47,2022-12-31,1940.0,150.0,13299.0,8267.0,5032.0,2020-12-31,-1.02,0.09
48,2023-03-31,2096.0,150.0,13614.0,8014.0,5600.0,2021-03-31,1.76,0.07
49,2023-06-30,2150.0,1044.0,14923.0,7997.0,6926.0,2021-06-30,12.24,0.10
50,2023-09-30,2288.0,242.0,15091.0,7909.0,7182.0,2021-09-30,4.98,0.08
51,2023-12-31,2437.0,295.0,17387.0,9759.0,7628.0,2021-12-31,5.72,0.08
52,2024-03-31,2603.0,347.0,17544.0,9437.0,8107.0,2022-03-31,4.01,0.33
53,2024-06-30,2627.0,262.0,18207.0,9541.0,8666.0,2022-06-30,2.48,1.68
54,2024-09-30,2797.0,432.0,18434.0,9144.0,9290.0,2022-09-30,2.30,3.08
55,2024-12-31,2957.0,384.0,20383.0,10774.0,9609.0,2022-12-31,1.32,4.33
56,2025-03-31,3088.0,460.0,20972.0,10833.0,10139.0,2023-03-31,2.28,4.83
57,2025-06-30,3215.0,385.0,22051.0,11119.0,10932.0,2023-06-30,2.83,5.12
58,2025-09-30,3407.0,502.0,21789.0,10488.0,11301.0,2023-09-30,3.24,5.33
59,2025-12-31,3568.0,401.0,NaN,NaN,NaN,2023-12-31,3.20,5.33

In [7]:
stock = pd.merge(stock, prices, left_on='date', right_on='Date', how='inner')
stock.drop(columns=['Date', 'Unnamed: 0', 'calendar_quarter'], inplace=True)  # Drop redundant columns if necessary
# Reorder columns to have 'date' first and Price next to it
cols = stock.columns.tolist()
cols.insert(1, cols.pop(cols.index('Price')))
stock = stock[cols]
stock

,date,Price,revenue_musd,net_income_musd,total_assets_musd,total_liabilities_musd,share_holder_equity_musd,date_y,gdp_growth,interest_rate
0,2012-06-30,4.920000,57.0,-9.0,200.0,175.0,25.0,2010-06-30,2.91,0.18
1,2012-09-30,7.736000,64.0,-13.0,382.0,191.0,191.0,2010-09-30,3.34,0.19
2,2012-12-31,6.006000,75.0,-10.0,478.0,235.0,243.0,2010-12-31,2.78,0.17
3,2013-03-31,7.240000,86.0,-13.0,516.0,252.0,264.0,2011-03-31,2.04,0.10
4,2013-06-30,8.078000,102.0,-21.0,542.0,274.0,268.0,2011-06-30,1.74,0.07
5,2013-09-30,10.390000,111.0,-15.0,579.0,291.0,288.0,2011-09-30,0.94,0.07
6,2013-12-31,11.202000,125.0,-24.0,1168.0,774.0,394.0,2011-12-31,1.54,0.08
7,2014-03-31,11.984000,139.0,-43.0,1224.0,821.0,404.0,2012-03-31,2.64,0.14
8,2014-06-30,12.392000,167.0,-50.0,1262.0,864.0,398.0,2012-06-30,2.40,0.16
9,2014-09-30,11.756000,179.0,-41.0,1305.0,887.0,417.0,2012-09-30,2.57,0.16
10,2014-12-31,13.570000,198.0,-45.0,1425.0,996.0,429.0,2012-12-31,1.55,0.14
11,2015-03-31,15.756000,212.0,-58.0,1494.0,1039.0,455.0,2013-03-31,1.70,0.15
12,2015-06-30,14.862000,247.0,-62.0,1563.0,1100.0,463.0,2013-06-30,1.52,0.09
13,2015-09-30,13.890000,261.0,-41.0,1663.0,1146.0,517.0,2013-09-30,2.24,0.09
14,2015-12-31,17.312000,286.0,-37.0,1807.0,1240.0,567.0,2013-12-31,3.01,0.07
15,2016-03-31,12.236000,306.0,-333.0,1874.0,1572.0,302.0,2014-03-31,1.65,0.09
16,2016-06-30,13.280000,341.0,-50.0,1714.0,1390.0,324.0,2014-06-30,2.69,0.09
17,2016-09-30,15.830000,358.0,-36.0,1813.0,1451.0,363.0,2014-09-30,3.06,0.09
18,2016-12-31,14.868000,386.0,5.0,2034.0,1647.0,387.0,2014-12-31,2.69,0.11
19,2017-03-31,17.493999,429.0,-22.0,2170.0,1743.0,427.0,2015-03-31,3.97,0.12
20,2017-06-30,21.200001,448.0,-56.0,2924.0,2442.0,482.0,2015-06-30,3.28,0.13
21,2017-09-30,23.506001,492.0,-22.0,3070.0,2518.0,551.0,2015-09-30,2.45,0.12
22,2017-12-31,26.077999,549.0,-17.0,3550.0,2772.0,779.0,2015-12-31,2.12,0.34
23,2018-03-31,33.090000,589.0,11.0,3704.0,2839.0,865.0,2016-03-31,1.80,0.37
24,2018-06-30,34.493999,631.0,-53.0,3473.0,2581.0,892.0,2016-06-30,1.49,0.39
25,2018-09-30,39.125999,673.0,8.0,3581.0,2561.0,1020.0,2016-09-30,1.81,0.40
26,2018-12-31,35.610001,715.0,7.0,3879.0,2768.0,1111.0,2016-12-31,2.18,0.65
27,2019-03-31,49.298000,789.0,-2.0,4399.0,3204.0,1195.0,2017-03-31,2.09,0.90
28,2019-06-30,54.914001,834.0,-11.0,4603.0,3342.0,1261.0,2017-06-30,2.33,1.15
29,2019-09-30,50.770000,886.0,41.0,4757.0,3327.0,1429.0,2017-09-30,2.41,1.15
30,2019-12-31,56.464001,951.0,599.0,6022.0,3894.0,2128.0,2017-12-31,2.99,1.41
31,2020-03-31,57.316002,1046.0,48.0,6197.0,3931.0,2266.0,2018-03-31,3.33,1.69
32,2020-06-30,81.012001,1071.0,41.0,6521.0,4043.0,2479.0,2018-06-30,3.30,1.91
33,2020-09-30,97.000000,1152.0,13.0,7705.0,5032.0,2674.0,2018-09-30,3.13,2.19
34,2020-12-31,110.085999,1250.0,17.0,8715.0,5881.0,2834.0,2018-12-31,2.13,2.40
35,2021-03-31,100.022003,1360.0,82.0,8822.0,5785.0,3037.0,2019-03-31,1.93,2.42
36,2021-06-30,109.910004,1409.0,59.0,9187.0,5912.0,3275.0,2019-06-30,2.24,2.40
37,2021-09-30,124.454002,1512.0,63.0,9478.0,5944.0,3534.0,2019-09-30,2.80,1.83
38,2021-12-31,129.822006,1615.0,26.0,10798.0,7103.0,3695.0,2019-12-31,3.35,1.55
39,2022-03-31,111.377998,1722.0,75.0,10993.0,6996.0,3997.0,2020-03-31,1.28,0.05
40,2022-06-30,95.103996,1752.0,20.0,11102.0,6908.0,4194.0,2020-06-30,-7.50,0.09
41,2022-09-30,75.522003,1831.0,80.0,11106.0,6583.0,4523.0,2020-09-30,-1.41,0.09
42,2022-12-31,77.653999,1940.0,150.0,13299.0,8267.0,5032.0,2020-12-31,-1.02,0.09
43,2023-03-31,92.944000,2096.0,150.0,13614.0,8014.0,5600.0,2021-03-31,1.76,0.07
44,2023-06-30,112.393997,2150.0,1044.0,14923.0,7997.0,6926.0,2021-06-30,12.24,0.10
45,2023-09-30,111.792000,2288.0,242.0,15091.0,7909.0,7182.0,2021-09-30,4.98,0.08
46,2023-12-31,141.298004,2437.0,295.0,17387.0,9759.0,7628.0,2021-12-31,5.72,0.08
47,2024-03-31,152.479996,2603.0,347.0,17544.0,9437.0,8107.0,2022-03-31,4.01,0.33
48,2024-06-30,157.334000,2627.0,262.0,18207.0,9541.0,8666.0,2022-06-30,2.48,1.68
49,2024-09-30,178.878006,2797.0,432.0,18434.0,9144.0,9290.0,2022-09-30,2.30,3.08
50,2024-12-31,212.024002,2957.0,384.0,20383.0,10774.0,9609.0,2022-12-31,1.32,4.33
51,2025-03-31,159.227997,3088.0,460.0,20972.0,10833.0,10139.0,2023-03-31,2.28,4.83
52,2025-06-30,205.615997,3215.0,385.0,22051.0,11119.0,10932.0,2023-06-30,2.83,5.12
53,2025-09-30,184.056000,3407.0,502.0,21789.0,10488.0,11301.0,2023-09-30,3.24,5.33
54,2025-12-31,153.190002,3568.0,401.0,NaN,NaN,NaN,2023-12-31,3.20,5.33

In [8]:
stock.to_csv('adbe_data.csv')