In [5]:
import pandas as pd

In [6]:
funadamentals = pd.read_csv('/Users/jon/Desktop/Ironhack/Unit 7 - Final Project/Final-Project-Ironhack/Type of analysis/Analisis temporal/fundamentals/csv/tesla/quarterly/tesla_quarterly_all_metrics.csv')
macros = pd.read_csv('/Users/jon/Desktop/Ironhack/Unit 7 - Final Project/Final-Project-Ironhack/Type of analysis/Analisis temporal/macro/csv/macro_2009_2025.csv')
prices = pd.read_csv('/Users/jon/Desktop/Ironhack/Unit 7 - Final Project/Final-Project-Ironhack/Type of analysis/Analisis temporal/prices/csv/tesla/tesla_price.csv')

In [7]:
funadamentals

,date,revenue_musd,net_income_musd,total_assets_musd,total_liabilities_musd,share_holder_equity_musd
0,2010-06-30,28.0,-39.0,148.0,458.0,-310.0
1,2010-09-30,31.0,-35.0,362.0,142.0,220.0
2,2010-12-31,36.0,-51.0,386.0,179.0,207.0
3,2011-03-31,49.0,-49.0,407.0,240.0,168.0
4,2011-06-30,58.0,-59.0,646.0,298.0,348.0
...,...,...,...,...,...,...
56,2024-06-30,25500.0,1400.0,112832.0,45641.0,67191.0
57,2024-09-30,25182.0,2167.0,119852.0,49212.0,70640.0
58,2024-12-31,25707.0,2131.0,122070.0,48453.0,73617.0
59,2025-03-31,19335.0,409.0,125111.0,49755.0,75356.0
60,2025-06-30,22496.0,1172.0,128567.0,50556.0,78011.0

In [8]:
macros

          date  gdp_growth  interest_rate
0   2025-06-30        1.99           4.33
1   2025-03-31        1.99           4.33
2   2024-12-31        2.53           4.33
3   2024-09-30        2.72           4.83
4   2024-06-30        3.04           5.33
..         ...         ...            ...
61  2010-03-31        1.75           0.20
62  2009-12-31        0.11           0.11
63  2009-09-30       -3.13           0.12
64  2009-06-30       -3.98           0.16
65  2009-03-31       -3.23           0.15

[66 rows x 3 columns]

In [9]:
prices

     Unnamed: 0        Date       Price calendar_quarter
0             0  2010-06-30    1.588667          Q2 2010
1             1  2010-07-31    1.329333          Q3 2010
2             2  2010-08-31    1.298667          Q3 2010
3             3  2010-09-30    1.360667          Q3 2010
4             4  2010-10-31    1.456000          Q4 2010
..          ...         ...         ...              ...
179         179  2025-05-31  346.459991          Q2 2025
180         180  2025-06-30  317.660004          Q2 2025
181         181  2025-07-31  308.269989          Q3 2025
182         182  2025-08-31  333.869995          Q3 2025
183         183  2025-09-30  329.359985          Q3 2025

[184 rows x 4 columns]

In [10]:
microsoft = pd.merge(funadamentals, macros, on='date', how='inner')
microsoft = pd.merge(microsoft, prices, left_on='date', right_on='Date', how='inner')
microsoft.drop(columns=['Date', 'Unnamed: 0', 'calendar_quarter'], inplace=True)  # Drop redundant columns if necessary

# Reorder columns to have 'date' first and Price next to it
cols = microsoft.columns.tolist()
cols.insert(1, cols.pop(cols.index('Price')))
microsoft = microsoft[cols]
microsoft

,date,Price,revenue_musd,net_income_musd,total_assets_musd,total_liabilities_musd,share_holder_equity_musd,gdp_growth,interest_rate
0,2010-06-30,1.588667,28.0,-39.0,148.0,458.0,-310.0,2.91,0.18
1,2010-09-30,1.360667,31.0,-35.0,362.0,142.0,220.0,3.34,0.19
2,2010-12-31,1.775333,36.0,-51.0,386.0,179.0,207.0,2.78,0.17
3,2011-03-31,1.850000,49.0,-49.0,407.0,240.0,168.0,2.04,0.10
4,2011-06-30,1.942000,58.0,-59.0,646.0,298.0,348.0,1.74,0.07
...,...,...,...,...,...,...,...,...,...
56,2024-06-30,197.880005,25500.0,1400.0,112832.0,45641.0,67191.0,3.04,5.33
57,2024-09-30,261.630005,25182.0,2167.0,119852.0,49212.0,70640.0,2.72,4.83
58,2024-12-31,403.839996,25707.0,2131.0,122070.0,48453.0,73617.0,2.53,4.33
59,2025-03-31,259.160004,19335.0,409.0,125111.0,49755.0,75356.0,1.99,4.33
60,2025-06-30,317.660004,22496.0,1172.0,128567.0,50556.0,78011.0,1.99,4.33

In [11]:
microsoft.to_csv('tesla_data.csv')