In [4]:
import pandas as pd

In [5]:
funadamentals = pd.read_csv('/Users/jon/Desktop/Ironhack/Unit 7 - Final Project/Final-Project-Ironhack/Type of analysis/Analisis temporal/fundamentals/csv/apple/quarterly/apple_quarterly_all_metrics.csv')
macros = pd.read_csv('/Users/jon/Desktop/Ironhack/Unit 7 - Final Project/Final-Project-Ironhack/Type of analysis/Analisis temporal/macro/csv/macro_2009_2025.csv')
prices = pd.read_csv('/Users/jon/Desktop/Ironhack/Unit 7 - Final Project/Final-Project-Ironhack/Type of analysis/Analisis temporal/prices/csv/apple/apple_price.csv')

In [6]:
funadamentals

,date,revenue_musd,net_income_musd,total_assets_musd,total_liabilities_musd,share_holder_equity_musd
0,2009-03-31,9084.0,1620.0,43237.0,18926.0,24311.0
1,2009-06-30,9734.0,1828.0,48140.0,22252.0,25888.0
2,2009-09-30,12207.0,2532.0,47501.0,15861.0,31640.0
3,2009-12-31,15683.0,3378.0,53926.0,18158.0,35768.0
4,2010-03-31,13499.0,3074.0,57057.0,17709.0,39348.0
...,...,...,...,...,...,...
61,2024-06-30,85777.0,21448.0,331612.0,264904.0,66708.0
62,2024-09-30,94930.0,14736.0,364980.0,308030.0,56950.0
63,2024-12-31,124300.0,36330.0,344085.0,277327.0,66758.0
64,2025-03-31,95359.0,24780.0,331233.0,264437.0,66796.0
65,2025-06-30,94036.0,23434.0,331495.0,265665.0,65830.0

In [7]:
macros

          date  gdp_growth  interest_rate
0   2025-06-30        1.99           4.33
1   2025-03-31        1.99           4.33
2   2024-12-31        2.53           4.33
3   2024-09-30        2.72           4.83
4   2024-06-30        3.04           5.33
..         ...         ...            ...
61  2010-03-31        1.75           0.20
62  2009-12-31        0.11           0.11
63  2009-09-30       -3.13           0.12
64  2009-06-30       -3.98           0.16
65  2009-03-31       -3.23           0.15

[66 rows x 3 columns]

In [8]:
prices

     Unnamed: 0        Date       Price calendar_quarter
0             0  2008-09-30    3.412087          Q3 2008
1             1  2008-10-31    3.229864          Q4 2008
2             2  2008-11-30    2.781965          Q4 2008
3             3  2008-12-31    2.562217          Q4 2008
4             4  2009-01-31    2.705713          Q1 2009
..          ...         ...         ...              ...
200         200  2025-05-31  200.622314          Q2 2025
201         201  2025-06-30  204.937408          Q2 2025
202         202  2025-07-31  207.334702          Q3 2025
203         203  2025-08-31  232.139999          Q3 2025
204         204  2025-09-30  229.720001          Q3 2025

[205 rows x 4 columns]

In [9]:
microsoft = pd.merge(funadamentals, macros, on='date', how='inner')
microsoft = pd.merge(microsoft, prices, left_on='date', right_on='Date', how='inner')
microsoft.drop(columns=['Date', 'Unnamed: 0', 'calendar_quarter'], inplace=True)  # Drop redundant columns if necessary

# Reorder columns to have 'date' first and Price next to it
cols = microsoft.columns.tolist()
cols.insert(1, cols.pop(cols.index('Price')))
microsoft = microsoft[cols]
microsoft

,date,Price,revenue_musd,net_income_musd,total_assets_musd,total_liabilities_musd,share_holder_equity_musd,gdp_growth,interest_rate
0,2009-03-31,3.155715,9084.0,1620.0,43237.0,18926.0,24311.0,-3.23,0.15
1,2009-06-30,4.275764,9734.0,1828.0,48140.0,22252.0,25888.0,-3.98,0.16
2,2009-09-30,5.564229,12207.0,2532.0,47501.0,15861.0,31640.0,-3.13,0.12
3,2009-12-31,6.326139,15683.0,3378.0,53926.0,18158.0,35768.0,0.11,0.11
4,2010-03-31,7.054725,13499.0,3074.0,57057.0,17709.0,39348.0,1.75,0.20
...,...,...,...,...,...,...,...,...,...
61,2024-06-30,209.401932,85777.0,21448.0,331612.0,264904.0,66708.0,3.04,5.33
62,2024-09-30,231.920639,94930.0,14736.0,364980.0,308030.0,56950.0,2.72,4.83
63,2024-12-31,249.534180,124300.0,36330.0,344085.0,277327.0,66758.0,2.53,4.33
64,2025-03-31,221.587616,95359.0,24780.0,331233.0,264437.0,66796.0,1.99,4.33
65,2025-06-30,204.937408,94036.0,23434.0,331495.0,265665.0,65830.0,1.99,4.33

In [10]:
microsoft.to_csv('apple_data.csv')