In [1]:
import pandas as pd

In [2]:
fundamentals = pd.read_csv('/Users/jon/Desktop/Ironhack/Unit 7 - Final Project/Final-Project-Ironhack/Type of analysis/Time series analysis/fundamentals/csv/adobe/quarterly/adobe_quarterly_all_metrics.csv')
macros = pd.read_csv('/Users/jon/Desktop/Ironhack/Unit 7 - Final Project/Final-Project-Ironhack/Type of analysis/Time series analysis/macro/csv/macro_2009_2025.csv')
prices = pd.read_csv('/Users/jon/Desktop/Ironhack/Unit 7 - Final Project/Final-Project-Ironhack/Type of analysis/Time series analysis/prices/csv/adbee_price.csv')

In [3]:
fundamentals

,date,revenue_musd,net_income_musd,total_assets_musd,total_liabilities_musd,share_holder_equity_musd
0,2009-02-28,786.0,156.0,5888.0,1276.0,4611.0
1,2009-05-31,705.0,126.0,6064.0,1263.0,4801.0
2,2009-08-31,698.0,136.0,5962.0,1267.0,4695.0
3,2009-11-30,757.0,-32.0,7282.0,2392.0,4891.0
4,2010-02-28,859.0,127.0,7945.0,2774.0,5171.0
...,...,...,...,...,...,...
61,2024-05-31,5309.0,1573.0,30007.0,15164.0,14843.0
62,2024-08-31,5408.0,1684.0,29830.0,15285.0,14545.0
63,2024-11-30,5606.0,1683.0,30230.0,16125.0,14105.0
64,2025-02-28,5714.0,1811.0,29955.0,16860.0,13095.0
65,2025-05-31,5873.0,1691.0,28107.0,16659.0,11448.0

In [4]:
macros = macros.sort_values(by='date', ascending=True)
macros = macros.reset_index(drop=True)
macros

          date  gdp_growth  interest_rate
0   2009-03-31       -3.23           0.15
1   2009-06-30       -3.98           0.16
2   2009-09-30       -3.13           0.12
3   2009-12-31        0.11           0.11
4   2010-03-31        1.75           0.20
..         ...         ...            ...
61  2024-06-30        3.04           5.33
62  2024-09-30        2.72           4.83
63  2024-12-31        2.53           4.33
64  2025-03-31        1.99           4.33
65  2025-06-30        1.99           4.33

[66 rows x 3 columns]

In [5]:
prices

     Unnamed: 0        Date       Price calendar_quarter
0             0  2008-09-30   39.470001          Q3 2008
1             1  2008-10-31   26.639999          Q4 2008
2             2  2008-11-30   23.160000          Q4 2008
3             3  2008-12-31   21.290001          Q4 2008
4             4  2009-01-31   19.309999          Q1 2009
..          ...         ...         ...              ...
200         200  2025-05-31  415.089996          Q2 2025
201         201  2025-06-30  386.880005          Q2 2025
202         202  2025-07-31  357.690002          Q3 2025
203         203  2025-08-31  356.700012          Q3 2025
204         204  2025-09-30  354.369995          Q3 2025

[205 rows x 4 columns]

BEFORE MERGING MAKE SURE DATE COLUMN BETWEEN MACRO AND FUNDAMENTAL DATA CORRESPOND IF NOT THE DF WILL COME OUT EMPTY

In [6]:
#If dates on fundamentals coincide with macros, uncomment line 3, otherwise, use line 4 and 5. May have to adjust depending on the dataset.

#stock = pd.merge(funadamentals, macros, on='date', how='inner')
stock = pd.merge(fundamentals, macros, left_index=True, right_index=True, how="inner")
stock = stock.rename(columns={'date_x': 'date'})


stock

,date,revenue_musd,net_income_musd,total_assets_musd,total_liabilities_musd,share_holder_equity_musd,date_y,gdp_growth,interest_rate
0,2009-02-28,786.0,156.0,5888.0,1276.0,4611.0,2009-03-31,-3.23,0.15
1,2009-05-31,705.0,126.0,6064.0,1263.0,4801.0,2009-06-30,-3.98,0.16
2,2009-08-31,698.0,136.0,5962.0,1267.0,4695.0,2009-09-30,-3.13,0.12
3,2009-11-30,757.0,-32.0,7282.0,2392.0,4891.0,2009-12-31,0.11,0.11
4,2010-02-28,859.0,127.0,7945.0,2774.0,5171.0,2010-03-31,1.75,0.20
...,...,...,...,...,...,...,...,...,...
61,2024-05-31,5309.0,1573.0,30007.0,15164.0,14843.0,2024-06-30,3.04,5.33
62,2024-08-31,5408.0,1684.0,29830.0,15285.0,14545.0,2024-09-30,2.72,4.83
63,2024-11-30,5606.0,1683.0,30230.0,16125.0,14105.0,2024-12-31,2.53,4.33
64,2025-02-28,5714.0,1811.0,29955.0,16860.0,13095.0,2025-03-31,1.99,4.33
65,2025-05-31,5873.0,1691.0,28107.0,16659.0,11448.0,2025-06-30,1.99,4.33

In [7]:
stock = pd.merge(stock, prices, left_on='date', right_on='Date', how='inner')
stock.drop(columns=['Date', 'Unnamed: 0', 'calendar_quarter'], inplace=True)  # Drop redundant columns if necessary
# Reorder columns to have 'date' first and Price next to it
cols = stock.columns.tolist()
cols.insert(1, cols.pop(cols.index('Price')))
stock = stock[cols]
stock

,date,Price,revenue_musd,net_income_musd,total_assets_musd,total_liabilities_musd,share_holder_equity_musd,date_y,gdp_growth,interest_rate
0,2009-02-28,16.700001,786.0,156.0,5888.0,1276.0,4611.0,2009-03-31,-3.23,0.15
1,2009-05-31,28.180000,705.0,126.0,6064.0,1263.0,4801.0,2009-06-30,-3.98,0.16
2,2009-08-31,31.420000,698.0,136.0,5962.0,1267.0,4695.0,2009-09-30,-3.13,0.12
3,2009-11-30,35.080002,757.0,-32.0,7282.0,2392.0,4891.0,2009-12-31,0.11,0.11
4,2010-02-28,34.650002,859.0,127.0,7945.0,2774.0,5171.0,2010-03-31,1.75,0.20
...,...,...,...,...,...,...,...,...,...,...
61,2024-05-31,444.760010,5309.0,1573.0,30007.0,15164.0,14843.0,2024-06-30,3.04,5.33
62,2024-08-31,574.409973,5408.0,1684.0,29830.0,15285.0,14545.0,2024-09-30,2.72,4.83
63,2024-11-30,515.929993,5606.0,1683.0,30230.0,16125.0,14105.0,2024-12-31,2.53,4.33
64,2025-02-28,438.559998,5714.0,1811.0,29955.0,16860.0,13095.0,2025-03-31,1.99,4.33
65,2025-05-31,415.089996,5873.0,1691.0,28107.0,16659.0,11448.0,2025-06-30,1.99,4.33

In [8]:
stock.to_csv('adbe_data.csv')