In [1]:
import pandas as pd

In [2]:
fundamentals = pd.read_csv('/Users/jon/Desktop/Ironhack/Unit 7 - Final Project/Final-Project-Ironhack/Type of analysis/Analisis temporal/fundamentals/csv/crm/quarterly/salesforce_quarterly_all_metrics.csv')
macros = pd.read_csv('/Users/jon/Desktop/Ironhack/Unit 7 - Final Project/Final-Project-Ironhack/Type of analysis/Analisis temporal/macro/csv/macro_2009_2025.csv')
prices = pd.read_csv('/Users/jon/Desktop/Ironhack/Unit 7 - Final Project/Final-Project-Ironhack/Type of analysis/Analisis temporal/prices/csv/crm_price.csv')

In [3]:
fundamentals

,date,revenue_musd,net_income_musd,total_assets_musd,total_liabilities_musd,share_holder_equity_musd
0,2009-01-31,290.0,14.0,1480.0,797.0,682.0
1,2009-04-30,305.0,18.0,1468.0,729.0,739.0
2,2009-07-31,316.0,21.0,1557.0,754.0,802.0
3,2009-10-31,331.0,21.0,1643.0,773.0,871.0
4,2010-01-31,354.0,20.0,2460.0,1404.0,1057.0
...,...,...,...,...,...,...
61,2024-04-30,9133.0,1533.0,96180.0,36497.0,59683.0
62,2024-07-31,9325.0,1429.0,92180.0,34547.0,57633.0
63,2024-10-31,9444.0,1527.0,91395.0,32870.0,58525.0
64,2025-01-31,9993.0,1708.0,102928.0,41755.0,61173.0
65,2025-04-30,9829.0,1541.0,98610.0,37944.0,60666.0

In [4]:
macros = macros.sort_values(by='date', ascending=True)
macros = macros.reset_index(drop=True)
macros

          date  gdp_growth  interest_rate
0   2009-03-31       -3.23           0.15
1   2009-06-30       -3.98           0.16
2   2009-09-30       -3.13           0.12
3   2009-12-31        0.11           0.11
4   2010-03-31        1.75           0.20
..         ...         ...            ...
61  2024-06-30        3.04           5.33
62  2024-09-30        2.72           4.83
63  2024-12-31        2.53           4.33
64  2025-03-31        1.99           4.33
65  2025-06-30        1.99           4.33

[66 rows x 3 columns]

In [5]:
prices

     Unnamed: 0        Date       Price calendar_quarter
0             0  2008-09-30   11.994895          Q3 2008
1             1  2008-10-31    7.672767          Q4 2008
2             2  2008-11-30    7.092849          Q4 2008
3             3  2008-12-31    7.932987          Q4 2008
4             4  2009-01-31    6.594714          Q1 2009
..          ...         ...         ...              ...
200         200  2025-05-31  264.949860          Q2 2025
201         201  2025-06-30  272.690002          Q2 2025
202         202  2025-07-31  258.329987          Q3 2025
203         203  2025-08-31  256.250000          Q3 2025
204         204  2025-09-30  253.250397          Q3 2025

[205 rows x 4 columns]

BEFORE MERGING MAKE SURE DATE COLUMN BETWEEN MACRO AND FUNDAMENTAL DATA CORRESPOND IF NOT THE DF WILL COME OUT EMPTY

In [6]:
#If dates on fundamentals coincide with macros, uncomment line 3, otherwise, use line 4 and 5. May have to adjust depending on the dataset.

#stock = pd.merge(funadamentals, macros, on='date', how='inner')
stock = pd.merge(fundamentals, macros, left_index=True, right_index=True, how="inner")
stock = stock.rename(columns={'date_x': 'date'})


stock

,date,revenue_musd,net_income_musd,total_assets_musd,total_liabilities_musd,share_holder_equity_musd,date_y,gdp_growth,interest_rate
0,2009-01-31,290.0,14.0,1480.0,797.0,682.0,2009-03-31,-3.23,0.15
1,2009-04-30,305.0,18.0,1468.0,729.0,739.0,2009-06-30,-3.98,0.16
2,2009-07-31,316.0,21.0,1557.0,754.0,802.0,2009-09-30,-3.13,0.12
3,2009-10-31,331.0,21.0,1643.0,773.0,871.0,2009-12-31,0.11,0.11
4,2010-01-31,354.0,20.0,2460.0,1404.0,1057.0,2010-03-31,1.75,0.20
...,...,...,...,...,...,...,...,...,...
61,2024-04-30,9133.0,1533.0,96180.0,36497.0,59683.0,2024-06-30,3.04,5.33
62,2024-07-31,9325.0,1429.0,92180.0,34547.0,57633.0,2024-09-30,2.72,4.83
63,2024-10-31,9444.0,1527.0,91395.0,32870.0,58525.0,2024-12-31,2.53,4.33
64,2025-01-31,9993.0,1708.0,102928.0,41755.0,61173.0,2025-03-31,1.99,4.33
65,2025-04-30,9829.0,1541.0,98610.0,37944.0,60666.0,2025-06-30,1.99,4.33

In [7]:
stock = pd.merge(stock, prices, left_on='date', right_on='Date', how='inner')
stock.drop(columns=['Date', 'Unnamed: 0', 'calendar_quarter'], inplace=True)  # Drop redundant columns if necessary
# Reorder columns to have 'date' first and Price next to it
cols = stock.columns.tolist()
cols.insert(1, cols.pop(cols.index('Price')))
stock = stock[cols]
stock

,date,Price,revenue_musd,net_income_musd,total_assets_musd,total_liabilities_musd,share_holder_equity_musd,date_y,gdp_growth,interest_rate
0,2009-01-31,6.594714,290.0,14.0,1480.0,797.0,682.0,2009-03-31,-3.23,0.15
1,2009-04-30,10.609535,305.0,18.0,1468.0,729.0,739.0,2009-06-30,-3.98,0.16
2,2009-07-31,10.740882,316.0,21.0,1557.0,754.0,802.0,2009-09-30,-3.13,0.12
3,2009-10-31,14.064261,331.0,21.0,1643.0,773.0,871.0,2009-12-31,0.11,0.11
4,2010-01-31,15.749494,354.0,20.0,2460.0,1404.0,1057.0,2010-03-31,1.75,0.20
...,...,...,...,...,...,...,...,...,...,...
61,2024-04-30,266.952118,9133.0,1533.0,96180.0,36497.0,59683.0,2024-06-30,3.04,5.33
62,2024-07-31,257.286926,9325.0,1429.0,92180.0,34547.0,57633.0,2024-09-30,2.72,4.83
63,2024-10-31,290.121307,9444.0,1527.0,91395.0,32870.0,58525.0,2024-12-31,2.53,4.33
64,2025-01-31,340.623810,9993.0,1708.0,102928.0,41755.0,61173.0,2025-03-31,1.99,4.33
65,2025-04-30,268.284576,9829.0,1541.0,98610.0,37944.0,60666.0,2025-06-30,1.99,4.33

In [8]:
stock.to_csv('crm_data.csv')