In [1]:
import pandas as pd

In [2]:
funadamentals = pd.read_csv('/Users/jon/Desktop/Ironhack/Unit 7 - Final Project/Final-Project-Ironhack/Type of analysis/Analisis temporal/fundamentals/csv/microsoft/quarterly/microsoft_quarterly_all_metrics.csv')
macros = pd.read_csv('/Users/jon/Desktop/Ironhack/Unit 7 - Final Project/Final-Project-Ironhack/Type of analysis/Analisis temporal/macro/csv/macro_2009_2025.csv')
prices = pd.read_csv('/Users/jon/Desktop/Ironhack/Unit 7 - Final Project/Final-Project-Ironhack/Type of analysis/Analisis temporal/prices/csv/microsoft/microsoft_price.csv')

In [3]:
funadamentals

,date,revenue_musd,net_income_musd,total_assets_musd,total_liabilities_musd,share_holder_equity_musd
0,2009-03-31,13648.0,2977.0,68853.0,31910.0,36943.0
1,2009-06-30,13099.0,3045.0,77888.0,38330.0,39558.0
2,2009-09-30,12920.0,3574.0,81612.0,40400.0,41212.0
3,2009-12-31,19022.0,6662.0,82096.0,37813.0,44283.0
4,2010-03-31,14503.0,4006.0,84910.0,39200.0,45710.0
...,...,...,...,...,...,...
61,2024-06-30,64727.0,22036.0,512163.0,243686.0,268477.0
62,2024-09-30,65585.0,24667.0,523013.0,235290.0,287723.0
63,2024-12-31,69632.0,24108.0,533898.0,231203.0,302695.0
64,2025-03-31,70066.0,25824.0,562624.0,240733.0,321891.0
65,2025-06-30,76441.0,27233.0,619003.0,275524.0,343479.0

In [4]:
macros

          date  gdp_growth  interest_rate
0   2025-06-30        1.99           4.33
1   2025-03-31        1.99           4.33
2   2024-12-31        2.53           4.33
3   2024-09-30        2.72           4.83
4   2024-06-30        3.04           5.33
..         ...         ...            ...
61  2010-03-31        1.75           0.20
62  2009-12-31        0.11           0.11
63  2009-09-30       -3.13           0.12
64  2009-06-30       -3.98           0.16
65  2009-03-31       -3.23           0.15

[66 rows x 3 columns]

In [5]:
prices

     Unnamed: 0        Date       Price calendar_quarter
0             0  2008-09-30   19.394428          Q3 2008
1             1  2008-10-31   16.226210          Q4 2008
2             2  2008-11-30   14.792500          Q4 2008
3             3  2008-12-31   14.221869          Q4 2008
4             4  2009-01-31   12.509980          Q1 2009
..          ...         ...         ...              ...
200         200  2025-05-31  459.604431          Q2 2025
201         201  2025-06-30  496.593658          Q2 2025
202         202  2025-07-31  532.624390          Q3 2025
203         203  2025-08-31  506.690002          Q3 2025
204         204  2025-09-30  502.820007          Q3 2025

[205 rows x 4 columns]

In [6]:
microsoft = pd.merge(funadamentals, macros, on='date', how='inner')
microsoft = pd.merge(microsoft, prices, left_on='date', right_on='Date', how='inner')
microsoft.drop(columns=['Date', 'Unnamed: 0', 'calendar_quarter'], inplace=True)  # Drop redundant columns if necessary

# Reorder columns to have 'date' first and Price next to it
cols = microsoft.columns.tolist()
cols.insert(1, cols.pop(cols.index('Price')))
microsoft = microsoft[cols]
microsoft

,date,Price,revenue_musd,net_income_musd,total_assets_musd,total_liabilities_musd,share_holder_equity_musd,gdp_growth,interest_rate
0,2009-03-31,13.531229,13648.0,2977.0,68853.0,31910.0,36943.0,-3.23,0.15
1,2009-06-30,17.620026,13099.0,3045.0,77888.0,38330.0,39558.0,-3.98,0.16
2,2009-09-30,19.172707,12920.0,3574.0,81612.0,40400.0,41212.0,-3.13,0.12
3,2009-12-31,22.821438,19022.0,6662.0,82096.0,37813.0,44283.0,0.11,0.11
4,2010-03-31,22.032991,14503.0,4006.0,84910.0,39200.0,45710.0,1.75,0.20
...,...,...,...,...,...,...,...,...,...
61,2024-06-30,442.821350,64727.0,22036.0,512163.0,243686.0,268477.0,3.04,5.33
62,2024-09-30,427.093567,65585.0,24667.0,523013.0,235290.0,287723.0,2.72,4.83
63,2024-12-31,419.196533,69632.0,24108.0,533898.0,231203.0,302695.0,2.53,4.33
64,2025-03-31,374.087158,70066.0,25824.0,562624.0,240733.0,321891.0,1.99,4.33
65,2025-06-30,496.593658,76441.0,27233.0,619003.0,275524.0,343479.0,1.99,4.33

In [7]:
microsoft.to_csv('microsoft_data.csv')