In [33]:
import pandas as pd

In [34]:
funadamentals = pd.read_csv('/Users/jon/Desktop/Ironhack/Unit 7 - Final Project/Final-Project-Ironhack/Type of analysis/Analisis temporal/fundamentals/csv/nike/quarterly/nike_quarterly_all_metrics.csv')
macros = pd.read_csv('/Users/jon/Desktop/Ironhack/Unit 7 - Final Project/Final-Project-Ironhack/Type of analysis/Analisis temporal/macro/csv/macro_2009_2025.csv')
prices = pd.read_csv('/Users/jon/Desktop/Ironhack/Unit 7 - Final Project/Final-Project-Ironhack/Type of analysis/Analisis temporal/prices/python/nike/nike_price.csv')

In [35]:
funadamentals['date'] = pd.to_datetime(funadamentals['date'].str.strip())
macros['date'] = pd.to_datetime(macros['date'].str.strip())
prices['Date'] = pd.to_datetime(prices['Date'].str.strip())

In [36]:
funadamentals

,date,revenue_musd,net_income_musd,total_assets_musd,total_liabilities_musd,share_holder_equity_musd
0,2009-02-28,4441.0,244.0,12256.0,4045.0,8211.0
1,2009-05-31,4713.0,342.0,13250.0,4557.0,8693.0
2,2009-08-31,4799.0,513.0,13191.0,4100.0,9091.0
3,2009-11-30,4405.0,375.0,13358.0,4134.0,9224.0
4,2010-02-28,4733.0,497.0,13576.0,4147.0,9429.0
...,...,...,...,...,...,...
61,2024-05-31,12606.0,1500.0,38110.0,23680.0,14430.0
62,2024-08-31,11589.0,1051.0,37867.0,23923.0,13944.0
63,2024-11-30,12354.0,1163.0,37959.0,23922.0,14037.0
64,2025-02-28,11269.0,794.0,37793.0,23786.0,14007.0
65,2025-05-31,11097.0,211.0,36579.0,23366.0,13213.0

In [37]:
macros

         date  gdp_growth  interest_rate
0  2025-06-30        1.99           4.33
1  2025-03-31        1.99           4.33
2  2024-12-31        2.53           4.33
3  2024-09-30        2.72           4.83
4  2024-06-30        3.04           5.33
..        ...         ...            ...
61 2010-03-31        1.75           0.20
62 2009-12-31        0.11           0.11
63 2009-09-30       -3.13           0.12
64 2009-06-30       -3.98           0.16
65 2009-03-31       -3.23           0.15

[66 rows x 3 columns]

In [38]:
#When companies don't report earnings during the calendar quarter we have to forward fill the data
macros = macros.set_index('date').resample('ME').ffill().reset_index()

In [39]:
prices

     Unnamed: 0       Date      Price calendar_quarter
0             0 2008-09-30  13.345490          Q3 2008
1             1 2008-10-31  11.496272          Q4 2008
2             2 2008-11-30  10.622531          Q4 2008
3             3 2008-12-31  10.222830          Q4 2008
4             4 2009-01-31   9.070256          Q1 2009
..          ...        ...        ...              ...
200         200 2025-05-31  59.878819          Q2 2025
201         201 2025-06-30  70.672722          Q2 2025
202         202 2025-07-31  74.303856          Q3 2025
203         203 2025-08-31  76.970001          Q3 2025
204         204 2025-09-30  74.422501          Q3 2025

[205 rows x 4 columns]

In [40]:
microsoft = pd.merge(funadamentals, macros, on='date', how='inner')
microsoft = pd.merge(microsoft, prices, left_on='date', right_on='Date', how='inner')
microsoft.drop(columns=['Date', 'Unnamed: 0', 'calendar_quarter'], inplace=True)  # Drop redundant columns if necessary

# Reorder columns to have 'date' first and Price next to it
cols = microsoft.columns.tolist()
cols.insert(1, cols.pop(cols.index('Price')))
microsoft = microsoft[cols]
microsoft

,date,Price,revenue_musd,net_income_musd,total_assets_musd,total_liabilities_musd,share_holder_equity_musd,gdp_growth,interest_rate
0,2009-05-31,11.503123,4713.0,342.0,13250.0,4557.0,8693.0,-3.23,0.15
1,2009-08-31,11.216619,4799.0,513.0,13191.0,4100.0,9091.0,-3.98,0.16
2,2009-11-30,13.202310,4405.0,375.0,13358.0,4134.0,9224.0,-3.13,0.12
3,2010-02-28,13.810738,4733.0,497.0,13576.0,4147.0,9429.0,0.11,0.11
4,2010-05-31,14.846562,5077.0,522.0,14419.0,4665.0,9754.0,1.75,0.20
...,...,...,...,...,...,...,...,...,...
60,2024-05-31,92.213409,12606.0,1500.0,38110.0,23680.0,14430.0,2.90,5.33
61,2024-08-31,81.149361,11589.0,1051.0,37867.0,23923.0,13944.0,3.04,5.33
62,2024-11-30,77.060097,12354.0,1163.0,37959.0,23922.0,14037.0,2.72,4.83
63,2025-02-28,78.102379,11269.0,794.0,37793.0,23786.0,14007.0,2.53,4.33
64,2025-05-31,59.878819,11097.0,211.0,36579.0,23366.0,13213.0,1.99,4.33

In [41]:
microsoft.to_csv('nike_data.csv')

In [42]:
print(funadamentals.columns)
print(macros.columns)
print(prices.columns)

print(funadamentals['date'].dtype)
print(macros['date'].dtype)
print(prices['Date'].dtype)

Index(['date', 'revenue_musd', 'net_income_musd', 'total_assets_musd',
       'total_liabilities_musd', 'share_holder_equity_musd'],
      dtype='object')
Index(['date', 'gdp_growth', 'interest_rate'], dtype='object')
Index(['Unnamed: 0', 'Date', 'Price', 'calendar_quarter'], dtype='object')
datetime64[ns]
datetime64[ns]
datetime64[ns]