In [1]:
import pandas as pd

In [2]:
funadamentals = pd.read_csv('/Users/jon/Desktop/Ironhack/Unit 7 - Final Project/Final-Project-Ironhack/Type of analysis/Analisis temporal/fundamentals/csv/amd/quarterly/amd_quarterly_all_metrics.csv')
macros = pd.read_csv('/Users/jon/Desktop/Ironhack/Unit 7 - Final Project/Final-Project-Ironhack/Type of analysis/Analisis temporal/macro/csv/macro_2009_2025.csv')
prices = pd.read_csv('/Users/jon/Desktop/Ironhack/Unit 7 - Final Project/Final-Project-Ironhack/Type of analysis/Analisis temporal/prices/csv/amd/amd_price.csv')

In [3]:
funadamentals

,date,revenue_musd,net_income_musd,total_assets_musd,total_liabilities_musd,share_holder_equity_musd
0,2009-03-31,1177.0,-416.0,9052.0,9215.0,-163.0
1,2009-06-30,1184.0,-330.0,8683.0,9148.0,-465.0
2,2009-09-30,1396.0,-128.0,8747.0,9316.0,-569.0
3,2009-12-31,1646.0,1178.0,9078.0,8430.0,648.0
4,2010-03-31,1574.0,257.0,5232.0,4436.0,796.0
...,...,...,...,...,...,...
61,2024-06-30,5835.0,265.0,67886.0,11348.0,56538.0
62,2024-09-30,6819.0,771.0,69636.0,12651.0,56985.0
63,2024-12-31,7658.0,482.0,69226.0,11658.0,57568.0
64,2025-03-31,7438.0,709.0,71550.0,13669.0,57881.0
65,2025-06-30,7685.0,872.0,74820.0,15155.0,59665.0

In [4]:
macros

          date  gdp_growth  interest_rate
0   2025-06-30        1.99           4.33
1   2025-03-31        1.99           4.33
2   2024-12-31        2.53           4.33
3   2024-09-30        2.72           4.83
4   2024-06-30        3.04           5.33
..         ...         ...            ...
61  2010-03-31        1.75           0.20
62  2009-12-31        0.11           0.11
63  2009-09-30       -3.13           0.12
64  2009-06-30       -3.98           0.16
65  2009-03-31       -3.23           0.15

[66 rows x 3 columns]

In [5]:
prices

     Unnamed: 0        Date       Price calendar_quarter
0             0  2008-09-30    5.250000          Q3 2008
1             1  2008-10-31    3.500000          Q4 2008
2             2  2008-11-30    2.360000          Q4 2008
3             3  2008-12-31    2.160000          Q4 2008
4             4  2009-01-31    2.190000          Q1 2009
..          ...         ...         ...              ...
200         200  2025-05-31  110.730003          Q2 2025
201         201  2025-06-30  141.899994          Q2 2025
202         202  2025-07-31  176.309998          Q3 2025
203         203  2025-08-31  162.630005          Q3 2025
204         204  2025-09-30  163.201096          Q3 2025

[205 rows x 4 columns]

In [6]:
microsoft = pd.merge(funadamentals, macros, on='date', how='inner')
microsoft = pd.merge(microsoft, prices, left_on='date', right_on='Date', how='inner')
microsoft.drop(columns=['Date', 'Unnamed: 0', 'calendar_quarter'], inplace=True)  # Drop redundant columns if necessary

# Reorder columns to have 'date' first and Price next to it
cols = microsoft.columns.tolist()
cols.insert(1, cols.pop(cols.index('Price')))
microsoft = microsoft[cols]
microsoft

,date,Price,revenue_musd,net_income_musd,total_assets_musd,total_liabilities_musd,share_holder_equity_musd,gdp_growth,interest_rate
0,2009-03-31,3.050000,1177.0,-416.0,9052.0,9215.0,-163.0,-3.23,0.15
1,2009-06-30,3.870000,1184.0,-330.0,8683.0,9148.0,-465.0,-3.98,0.16
2,2009-09-30,5.660000,1396.0,-128.0,8747.0,9316.0,-569.0,-3.13,0.12
3,2009-12-31,9.680000,1646.0,1178.0,9078.0,8430.0,648.0,0.11,0.11
4,2010-03-31,9.270000,1574.0,257.0,5232.0,4436.0,796.0,1.75,0.20
...,...,...,...,...,...,...,...,...,...
61,2024-06-30,162.210007,5835.0,265.0,67886.0,11348.0,56538.0,3.04,5.33
62,2024-09-30,164.080002,6819.0,771.0,69636.0,12651.0,56985.0,2.72,4.83
63,2024-12-31,120.790001,7658.0,482.0,69226.0,11658.0,57568.0,2.53,4.33
64,2025-03-31,102.739998,7438.0,709.0,71550.0,13669.0,57881.0,1.99,4.33
65,2025-06-30,141.899994,7685.0,872.0,74820.0,15155.0,59665.0,1.99,4.33

In [7]:
microsoft.to_csv('apple_data.csv')